[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
name = "awesome"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b}"
interval = 2

[[block]]
block = "bluetooth"
mac = "04:52:C7:F0:5F:D6"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}Â°"
chip = "*-isa-*"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%d/%m/%Y %H:%M:%S"
